In [1]:
#from keras.models import load_model
#import imutils # Package of convenience functions
#from skimage import io
#import matplotlib.pyplot as plt
#import requests
#import timeit

In [2]:
# #############################################################################
# Importing necessary libraries for creating model
from keras.models import model_from_json
import os
import pandas as pd
import numpy as np
import keras
import cv2 # importing open CV library
import dlib   # For frontal face identity
from PIL import Image
import csv
import face_recognition # importing face recognition library
from sklearn.metrics import classification_report, confusion_matrix
import sys
from zipfile import ZipFile

Using TensorFlow backend.


In [3]:
# #############################################################################
# Unpack and extract images paths

# Create a ZipFile Object and load sample.zip in it
with ZipFile('../../OUI/OUI.zip', 'r') as zipObj:
   # Extract all the contents of zip file 
   zipObj.extractall('../OUI_unarchive')

images = []
if len(next(os.walk('../OUI_unarchive/OUI/'))[1]) == 0: #case when images are in one folder
    for image in os.listdir('../OUI_unarchive/OUI/'): 
        if image[-3:] == 'jpg' or image[-3:] == 'png':
            images.append('../OUI_unarchive/OUI/' + image)
else: #case when images are in several folders
    for path in ['../OUI_unarchive/OUI/' + next(os.walk('../OUI_unarchive/OUI/'))[1][n] for n in range(len(next(os.walk('../OUI_unarchive/OUI/'))[1]))]:
        for image in os.listdir(path+'/'): 
            if image[-3:] == 'jpg' or image[-3:] == 'png':
                images.append(path+'/' + image)
            
print('Total number of images:', len(images))

Total number of images: 19370


In [4]:

# #############################################################################
# loading the trained model and weights
json_file = open('../trained model/model.json', 'r')     # Loading the jason file
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("../trained model/model.h5")    # Loading the weights


def detect_faces(image):                    # Create a face detector
    face_detector = dlib.get_frontal_face_detector()
    detected_faces = face_detector(image, 1)    # Run detector and get bounding boxes of the faces on image
    face_frames = [(x.left(), x.top(),
                    x.right(), x.bottom()) for x in detected_faces]  # To identify the frame size
    return face_frames


def resize_im(image, hight, width):          # Resizing the image
    resized_im = image.resize((hight, width))
    return resized_im


def reshape(numpy_array):            # Reshape the image
    d = np.stack(numpy_array)
    reshaped = d.reshape(1, d.size)
    return reshaped


def GIGIDL(image_path):
    f = open("../storage.csv", "w")
    img= cv2.imread(image_path)
    detected_faces = detect_faces(img)
    for n, face_rect in enumerate(detected_faces):
                    fa = Image.fromarray(img).crop(face_rect)   # Cropping the face or faces
                    s = np.array(resize_im(fa, 100,100))
                    c = cv2.cvtColor(s, cv2.COLOR_BGR2GRAY)    # Converting the image
                    re_data = reshape(c)
                    np.savetxt(f, re_data, delimiter=",", fmt = '%d')  # Save the converted image data
                    cv2.waitKey(0)
                    cv2.destroyAllWindows()    # Need to kill the image window
    #reading the faces from the temp file
    data = pd.read_csv('../storage.csv', header = None)
    df_x = data.iloc[:,0:].values.reshape(len(data),100,100,1)   # Creating the requird formate
    f_x = np.array(df_x)  # Need to convert as a array
    loaded_model.compile(loss='categorical_crossentropy',optimizer = 'adadelta', metrics = ['accuracy'])
    prob = np.asmatrix(loaded_model.predict(f_x))
    if prob[0,0] > prob[0,1]:
             gender= 'f'
    if prob[0,0] < prob[0,1]:
             gender='m'
    return gender
    



In [5]:
with open('/Users/nadabeili/Desktop/Improved-Gender-Identifier/OUI.csv', 'w', newline='') as myfile:             # Here output written in the file
    wr = csv.writer(myfile,quoting=csv.QUOTE_ALL)
    wr.writerow(['Image_name','Pred_Gender'])

    for imagelocation in images:                        # Get the images location
            imageInfo = imagelocation.split('/')
            image =imageInfo[-1].split('.')
            imageName = imageInfo[-2]+'/'+'.'.join(image[-3:])
            try:
                GIGIDL_gender=GIGIDL(imagelocation)   # return the predicted gender
                wr = csv.writer(myfile,quoting=csv.QUOTE_ALL)
                wr.writerow([imageName,GIGIDL_gender])
            except:
                wr = csv.writer(myfile,quoting=csv.QUOTE_ALL)
                wr.writerow([imageName,'u'])   #if there is an error in returning gender , write undefined
                print("Oops!",sys.exc_info()[0],"occured.")
                print()

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <cla

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.

Oops! <class 'pandas.errors.EmptyDataError'> occured.



In [6]:
def annotation_ext(input_dir,output_dir):
    # Create a ZipFile Object and load sample.zip in it
    with ZipFile(input_dir, 'r') as zipObj:
    # Extract all the contents of zip file 
        zipObj.extractall(output_dir)
    files=[output_dir+'/'+name for name in os.listdir(output_dir) if os.path.isfile(os.path.join(output_dir, name))]
    df = pd.DataFrame()
    for file in files:
        data = pd.read_csv(file, sep="\t")  #load each file as dataframe
        df= df.append(data, ignore_index = True)
    df= df.astype(str)
    df['Image_name']=df['user_id']+'/'+ df['face_id']+'.'+df['original_image'] # make Image name similar to the one in the image path
    df= df[['Image_name','gender']] # keep only gender and imagename
    return df.drop_duplicates()

In [7]:
result= annotation_ext('../../OUI/OUI_annotations.zip','../OUI_annotations')
result

Image_name gender
0          30601258@N03/2.10424815813_e94629b1ec_o.jpg      m
1          30601258@N03/3.10437979845_5985be4b26_o.jpg      m
2          30601258@N03/2.11816644924_075c3d8d59_o.jpg      m
3          30601258@N03/4.10424595844_1009c687e4_o.jpg      f
4          30601258@N03/2.10190308156_5c748ab2da_o.jpg      m
...                                                ...    ...
13555  101515718@N03/2280.10587826073_6663f5b654_o.jpg      f
13556  101515718@N03/2278.10587571495_a61785cd06_o.jpg      m
13557  101515718@N03/2279.10587571495_a61785cd06_o.jpg      f
13558   113830953@N04/480.11855529986_dff116e018_o.jpg    nan
13559   113830953@N04/480.11855531166_90b5b3670d_o.jpg    nan

[13560 rows x 2 columns]

In [10]:
### Precision, recall, F1_score
#read the result_file
df_pred=pd.read_csv('/Users/nadabeili/Desktop/Improved-Gender-Identifier/OUI.csv')
result_data= pd.merge(result,df_pred, how= 'inner', on='Image_name')
result_data.to_csv('../all_result.csv')
result_data.dropna(inplace=True)
# True values
y_true = result_data['gender']
# Predicted values
y_pred = result_data['Pred_Gender']

# Print the confusion matrix
print(confusion_matrix(y_true, y_pred))
# Print the precision and recall, among other metrics
print(classification_report(y_true, y_pred, digits=4))

#printing the metrics
metrics_dict=classification_report(y_true, y_pred,output_dict=True)

#precision:
print('Precision:',round(metrics_dict['weighted avg']['precision'],4))
#Recall
print('Recall:',round(metrics_dict['weighted avg']['recall'],4))
#F1-score
print('F1-score:',round(metrics_dict['weighted avg']['f1-score'],4))
#accuracy
print('Accuracy:',round(metrics_dict['accuracy'],4))

[[1350 4883    0  189]
 [1282 4221    0  269]
 [ 143  403    0   23]
 [ 334  412    0   51]]


/Users/nadabeili/opt/anaconda3/envs/p36workshop/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           f     0.4342    0.2102    0.2833      6422
           m     0.4255    0.7313    0.5380      5772
         nan     0.0000    0.0000    0.0000       569
           u     0.0959    0.0640    0.0767       797

    accuracy                         0.4146     13560
   macro avg     0.2389    0.2514    0.2245     13560
weighted avg     0.3924    0.4146    0.3677     13560

Precision: 0.3924
Recall: 0.4146
F1-score: 0.3677
Accuracy: 0.4146


In [9]:
result_data

Image_name gender Pred_Gender
0          30601258@N03/2.10424815813_e94629b1ec_o.jpg      m           m
1          30601258@N03/3.10437979845_5985be4b26_o.jpg      m           m
2          30601258@N03/2.11816644924_075c3d8d59_o.jpg      m           m
3          30601258@N03/4.10424595844_1009c687e4_o.jpg      f           m
4          30601258@N03/2.10190308156_5c748ab2da_o.jpg      m           m
...                                                ...    ...         ...
13555  101515718@N03/2280.10587826073_6663f5b654_o.jpg      f           m
13556  101515718@N03/2278.10587571495_a61785cd06_o.jpg      m           m
13557  101515718@N03/2279.10587571495_a61785cd06_o.jpg      f           m
13558   113830953@N04/480.11855529986_dff116e018_o.jpg    nan           m
13559   113830953@N04/480.11855531166_90b5b3670d_o.jpg    nan           f

[13560 rows x 3 columns]